<div class="b_troop">
<?php  require_once('.//lib/form.php');  require_once('.//lib/dbo.php');  require_once('.//eng/main/troop.php');  if($town->$u == 0)  {   echo $lang['BuildBuilding'].'</div>';   return;  }  $sql = $dbo->ExectueQuery(sprintf('SELECT * FROM `%stroop_info` WHERE `kind` = \'%s\' ORDER BY `id` LIMIT 11,1',DB_PERFIX,$account->kind));  $i = 0;  $list = array();  while($row = $dbo->Read($sql))  {   $row['times'] = round($row['times'] *(ONE_TICK/ONE_HOUR));   $list[$i++] = new Object($row);   $form->AddModal('mo'.$i,$row['name'],sprintf('<img src="img/troop/b/%d_%d.gif" class="bigimg" alt="%s"/>%s',    $account->kind, $i + 11, $row['name'], $row['desc']), $form->TroopInfo(    $row['r1'],$row['r2'],$row['r3'],$row['r4'],$row['r5'],    SecToString($row['times']),$troops[$account->kind][$i + 11][8],    $troops[$account->kind][$i + 11][0],$troops[$account->kind][$i  + 11][1],$troops[$account->kind][$i + 11][2],    $troops[$account->kind][$i + 11][3],$troops[$account->kind][$i  + 11][4],$troops[$account->kind][$i + 11][5]));  }  $hitem = $hero->GetItems();  $bph = 0;  if(isset($hitem[1]))  {   if($hitem[1]->t2 == 5)    $bph = $hitem[1]->t3 * SPACIAL_HERO_ITEM_TRAIN;  }  $dbo->Cancel($sql);  $bph += $town->$u * 3;  $bph /= 100;  if(isset($_POST['com']) and $_POST['com'] == TERAIN_TROOP)  {   $_POST['tbT1'] = isset($_POST['tbT1'])? ValidNumber($_POST['tbT1'],true): 0;   if(!($town->res_u & 2048))    $_POST['tbT1'] = 0;   $t = MaxTrain($list[0]);   if($_POST['tbT1'] and $_POST['tbT1'] > $t)    $_POST['tbT1'] = $t;   if($town->Lock())   {    if($_POST['tbT1'])     $town->TrainTroop( 15, 12, $list[0]->times - ($list[0]->times * $bph), $_POST['tbT1'],       $list[0]->r1,$list[0]->r2,$list[0]->r3,$list[0]->r4,$list[0]->r5, $troops[$account->kind][12][8]);   }   $town->UnLock();  }  ?>
<form action="<?php printf('building.php?bid=%s&amp;tid=%s',$bid,$town->id);?>" method="post">
<input type="hidden" name="com" value="<?php echo TERAIN_TROOP;?>"  />
<table>
<tr><td><?php echo $lang['Troops'];?></td><td><?php echo $lang['Cost'];?></td><td><?php echo $lang['CurrentT'];?></td><td colspan="2"><?php echo $lang['Number'];?></td><td><?php echo $lang['Action'];?></td></tr>

<tr><td><img src="img/troop/s/<?php echo $account->kind;?>_12.gif" class = "i30s" onclick="modal.Show('mo1');" alt = "<?php echo $list[0]->name;?>"/></td>
<?php  if(!($town->res_u & 2048))   printf('<td colspan="5">%s</td>',sprintf($lang['NoResearchT'],$list[0]->name));  else  {  ?>
<td><?php $form->EchoCost($list[0]->r1,$list[0]->r2,$list[0]->r3,$list[0]->r4,$list[0]->r5,SecToString($list[0]->times - ceil($list[0]->times * $bph)), $troops[$account->kind][7][8]); ?></td><td><?php echo $town->t7;?></td><td><?php  printf('<a href="javascript:void(0);" onclick="SetValues(\'tbT1\',this.innerHTML);">%s</a>',MaxTrain($list[0]));  ?></td><td><input type="text" value="0" name="tbT1" id="tbT1"  /></td><td><input type="submit" value="<?php echo $lang['Training'];?>" /></td>
<?php  }?></tr>
</table>
</form>
<table>
<tr><td class="center"  colspan="6"><?php echo $lang['TrainingTroop'];?></td></tr>

<tr><td><?php echo $lang['Troops'];?></td><td><?php echo $lang['Number'];?></td><td colspan="2"><?php echo $lang['TimeProcess'];?></td><td><?php echo $lang['EndTime'];?></td><td><?php echo $lang['InDate'];?></td></tr>
<?php  $sql = $dbo->ExectueQuery(sprintf('SELECT * FROM `%stroop_t` WHERE `tid` = \'%s\' AND  `bid` = \'15\' AND `d` = \'0\' ORDER BY `end`',   DB_PERFIX,$town->id));    if(!$dbo->RowsNumber($sql))   printf('<tr><td class="center"  colspan="6">%s</td></tr>',$lang['NoRecord']);  else  {   $i = 0;   while($row = $dbo->Read($sql))   {    $start = $row['start'];    $end = $row['end'];    $modify = $town->modify;    $last = 0;    if($start > $_SERVER['REQUEST_TIME'])    {     $num = (int)floor(($end - $start)/$row['et']);     $last = ($start - $_SERVER['REQUEST_TIME']) + $row['et'];    }    else    {     if($end > time())     {      $num = (int)floor(($end - $_SERVER['REQUEST_TIME'])/$row['et']);      $last = ($end - $_SERVER['REQUEST_TIME']) - $num *$row['et'];      $num++;     }     else     {      $num = $last = 0;     }    }    $tt = 1;     printf('<tr><td><img src="img/troop/s/%s_%s.gif" class = "i30s" onclick="modal.Show(\'mo%s\');" alt = "%s"/></td><td id ="ttp%sn">%s</td><td id ="ttp%sl">%s</td><td class="ttrain" id ="ttp%d">%s</td><td style="min-width:80px;">%s</td><td>%s</td></tr>',    $account->kind,$row['tt'],$tt,$list[$tt - 1]->name,$i,$num,$i,SecToString($row['et']),$i,SecToString($last),    Until($end,'ttimer'.$i),DateToString($end));    $i++;   }  }  $dbo->Cancel($sql);  ?>
</table>
</div>