<div class="b_troop">
<?php  require_once('.//lib/form.php');  require_once('.//lib/dbo.php');  require_once('.//eng/main/troop.php');  require_once('.//lib/defines.php');  if($town->$u == 0)  {   echo $lang['BuildBuilding'].'</div>';   return;  }  $research = array();  $sql = $dbo->ExectueQuery(sprintf('SELECT * FROM `%sresearch` WHERE `kind` = \'%s\' AND `tid` = \'%s\' AND `d` = \'0\'',   DB_PERFIX, RES_UPGRADE, $town->id));  while($row = $dbo->Read($sql))   $research[$row['subkind']] = $row;  $dbo->Cancel($sql);  gc_collect_cycles();  $one = 1;  if(isset($_POST['com']) and $_POST['com'] == RESEARCH_UPGRADE)  {   $_POST['kind'] = isset($_POST['kind']) ? ValidNumber($_POST['kind'],true): 0;   if($_POST['kind'] and ($town->res_u & ($one << $_POST['kind'] - 1)) and $_POST['kind'] <12)   {    if(!isset($research[$_POST['kind']]))    {     $count = $dbo->ExectueScaler(sprintf('SELECT COUNT(*) AS `c` FROM `%sresearch` WHERE `tid` = \'%s\' AND `kind` = \'%s\' AND `d` = \'0\'',      DB_PERFIX, $town->id, RES_UPGRADE), 'c');     if(!($count > 1 or ($count and !$plus->HavePlus('pb'))))     {      $up = 'up'.$_POST['kind'];      $row = $dbo->ExectueRow(sprintf('SELECT * FROM `troop_info` WHERE `id` = \'%s\'',($account->kind -1)*14 + $_POST['kind']));      if($town->HaveEnough($row['r1'] * ($town->$up +10),$row['r2'] * ($town->$up +10),$row['r3'] * ($town->$up +10),$row['r4'] * ($town->$up +10),$row['r5']* ($town->$up +10)))      {       $bt = ceil($_SERVER['REQUEST_TIME'] + ($row['times'] - ($row['times'] * $town->$u * 0.03))* 50);       $town->Research($_POST['kind'],$row['r1'] * ($town->$up +10),$row['r2'] * ($town->$up +10),$row['r3'] * ($town->$up +10),$row['r4'] * ($town->$up +10),$row['r5']* ($town->$up +10), $bt, RES_UPGRADE);      }     }    }   }  }  $research = array();  $sql = $dbo->ExectueQuery(sprintf('SELECT * FROM `%sresearch` WHERE `kind` = \'%s\' AND `tid` = \'%s\' AND `d` = \'0\'',   DB_PERFIX, RES_UPGRADE, $town->id));  while($row = $dbo->Read($sql))   $research[$row['subkind']] = $row;  $dbo->Cancel($sql);  gc_collect_cycles();  $sql = $dbo->ExectueQuery(sprintf('SELECT * FROM `%stroop_info` WHERE `kind` = \'%s\' ORDER BY `id`',DB_PERFIX,$account->kind));  $i = 0;  $j = 0;  $list = array();  while($row = $dbo->Read($sql))  {   $i++;   $list[$i] = new Object($row);   $form->AddModal('mo'.$i,$row['name'],sprintf('<img src="img/troop/b/%d_%d.gif" class="bigimg" alt="%s"/>%s',    $account->kind,$i,$row['name'],$row['desc']),$form->TroopInfo(    $row['r1'],$row['r2'],$row['r3'],$row['r4'],$row['r5'],    SecToString($row['times']),1,    $troops[$account->kind][$i][0],$troops[$account->kind][$i][1],$troops[$account->kind][$i][2],    $troops[$account->kind][$i][3],$troops[$account->kind][$i][4],$troops[$account->kind][$i][5]));  }  $dbo->Cancel($sql);  gc_collect_cycles();  ?>
<form action="<?php printf('building.php?bid=%s&amp;tid=%s',$bid,$town->id);?>" method="post">
<input type="hidden" name="com" value="<?php echo RESEARCH_UPGRADE?>"  />
<input type="hidden" name="kind" id = "kind" value="?"  />
<table>
<tr><td><?php echo $lang['Troops'];?></td><td><?php echo $lang['Level'];?></td><td><?php echo $lang['Cost'];?></td><td style="min-width:80px;"><?php echo $lang['Action'];?></td></tr>
<?php  $i = 0;  $count = count($research);  $j =0;  foreach($list as &$l)  {   $i++;      if($i> 11)          break;   if(!($town->res_u &($one <<$i -1)))    continue;   $up = "up$i";      if($town->$up >= $info['lvl'])          continue;      $j++;   printf('<tr><td><img src="img/troop/s/%d_%d.gif" class = "i30s" onclick="modal.Show(\'mo%d\');" alt = "%s" /></td><td>%s</td><td>',    $account->kind,$i,$i,$l->name,$town->$up);   $acthion = sprintf('<input type="submit" value="%s" onclick="SetValues(\'kind\',\'%d\');"  />',$lang['Research'],$i);   if(!$town->HaveEnough($l->r1 * ($town->$up +10),$l->r2 * ($town->$up +10),$l->r3 * ($town->$up +10),$l->r4 * ($town->$up +10),$l->r5 * ($town->$up +10)))    $acthion = sprintf($lang['NotEnough'],$lang['Resource']);   if($count > 1 or ($count and !$plus->HavePlus('pb')))    $acthion = sprintf($lang['MaxPermission'],$lang['Research']);   if(isset($research[$i]))    $acthion = $form->Addtimer($research[$i]['modify'],sprintf('building.php?bid=%s&tid=%s',$bid,$town->id));   if($town->$up > $town->$u)     $acthion = $lang['LowLevel'];   if($town->$up == $info['lvl'])    $acthion = sprintf($lang['bMaxLevel'],$l->name);   $bt = ceil(($l->times - ($l->times * $town->$u * 0.03))* 50);   $form->EchoCost($l->r1 * ($town->$up +10),$l->r2 * ($town->$up +10),$l->r3 * ($town->$up +10),$l->r4 * ($town->$up +10),$l->r5 * ($town->$up +10),    SecToString($bt),0);   printf('</td><td>%s</td></tr>', $acthion);  }  if(!$j)     printf('<tr><td colspan="4">%s</td></tr>',$lang['NoRecord']);  ?>
</table>
</form>
</div>