<div class="b_troop">
<?php  require_once('.//lib/form.php');  require_once('.//lib/dbo.php');  require_once('.//lib/defines.php');  if($town->$u == 0)  {   echo $lang['BuildBuilding'].'</div>';   return;  }  $research = array();  $sql = $dbo->ExectueQuery(sprintf('SELECT * FROM `%sresearch` WHERE `kind` = \'%s\' AND `tid` = \'%s\' AND `d` = \'0\'',   DB_PERFIX, RES_ELIXIR, $town->id));  while($row = $dbo->Read($sql))   $research[$row['subkind']] = $row;  $dbo->Cancel($sql);  gc_collect_cycles();    $one = 1;  if(isset($_POST['com']) and $_POST['com'] == RESEARCH_ELIXIR)  {   $_POST['kind'] = isset($_POST['kind']) ? ValidNumber($_POST['kind'],true): 0;   if($_POST['kind'] or $_POST['kind'] < 16 or !($town->res_e & ($one << $_POST['kind'] - 1)))   if(!isset($research[$_POST['kind']]))   {    $count = $dbo->ExectueScaler(sprintf('SELECT COUNT(*) AS `c` FROM `%sresearch` WHERE `tid` = \'%s\' AND `kind` = \'%s\' AND `d` = \'0\'',      DB_PERFIX, $town->id, RES_ELIXIR), 'c');    if(!($count > 1 or ($count and !$plus->HavePlus('pb'))))    {     if($town->Lock())     {      $town = $account->GetTown($town->id);      $row = $dbo->ExectueRow(sprintf('SELECT * FROM `%selixir_i` WHERE `id` = \'%s\'',DB_PERFIX, $_POST['kind']));      if($town->HaveEnough($row['r1'] * 5,$row['r2'] * 5,$row['r3'] * 5,$row['r4'] * 5,$row['r5'] * 5))      {       $bt = (int)ceil($_SERVER['REQUEST_TIME'] + ($row['times'] -($row['times'] * $town->$u * 0.03))*10);       $town->Research($_POST['kind'], $row['r1'] * 5, $row['r2'] * 5, $row['r3'] * 5,$row['r4'] * 5,$row['r5']*5, $bt, RES_ELIXIR);      }     }     $town->UnLock();    }   }  }  $research = array();  $sql = $dbo->ExectueQuery(sprintf('SELECT * FROM `%sresearch` WHERE `kind` = \'%s\' AND `tid` = \'%s\' AND `d` = \'0\'',   DB_PERFIX, RES_ELIXIR, $town->id));  while($row = $dbo->Read($sql))   $research[$row['subkind']] = $row;  $dbo->Cancel($sql);  gc_collect_cycles();  $list = array();  $sql = $dbo->ExectueQuery(sprintf('SELECT * FROM `%selixir_i`',DB_PERFIX));  $one = 1;  $i =0;  while($row = $dbo->Read($sql))  {   $list[$row['id']] = new Object($row);   $form->AddModal('mo'.$row['id'],$row['name'],sprintf('<img src="img/eli/%d.gif" alt="%s"/>%s',    $row['id'],$row['name'],$row['desc']));  }  $dbo->Cancel($sql);  gc_collect_cycles();  ?>
<form action="<?php printf('building.php?bid=%s&amp;tid=%s',$bid,$town->id);?>" method="post">
<input type="hidden" name="com" value="<?php echo RESEARCH_ELIXIR?>"  />
<input type="hidden" name="kind" id = "kind" value="?"  />
<table>
<tr><td><?php echo $lang['Elixir'];?></td><td><?php echo $lang['Cost'];?></td><td><?php echo $lang['Level'];?></td><td style="min-width:80px;"><?php echo $lang['Action'];?></td></tr>
<?php  $count = count($research);  $j =0;  $i = 0;  foreach($list as &$l)  {   $i++;   if(($town->res_e &($one <<$i - 1)))    continue;   $j++;   printf('<tr><td><img src="img/eli/%d.gif" class = "i30s" onclick="modal.Show(\'mo%d\');" alt = "%s" /></td><td>',    $l->id,$l->id,$l->name);   $acthion =  $town->HaveEnough($l->r1 * 5,$l->r2 * 5,$l->r3 * 5,$l->r4 * 5,$l->r5 * 5) ?     sprintf('<input type="submit" value="%s" onclick="SetValues(\'kind\',\'%d\');"  />',$lang['Research'],$l->id):    sprintf($lang['NotEnough'],$lang['Resource']);   if($count > 1 or ($count and !$plus->HavePlus('pb')))    $acthion = sprintf($lang['MaxPermission'],$lang['Research']);   if($l->lvl > $town->$u)    $acthion = $lang['NoRequirement'];   if(isset($research[$l->id]))    $acthion = Until($research[$l->id]['modify'],'reid'.$l->id);   $bt = ceil(($l->times - ($l->times  * $town->$u * 0.03))*10);   $form->EchoCost($l->r1 * 5,$l->r2 * 5,$l->r3 * 5,$l->r4 * 5,$l->r5 * 5,SecToString($bt),0);   printf('</td><td>%s</td><td>%s</td></tr>', $l->lvl,$acthion);  }  if(!$j)   printf('<tr><td colspan="4">%s</td></tr>',$lang['NoRecord']);  ?>
</table>
</form>
</div>