<div class="b_troop">
<?php  require_once('.//lib/form.php');  require_once('.//eng/main/town.php');  require_once('.//lib/dbo.php');  require_once('.//lib/defines.php');  require_once('.//eng/main/elixir.php');    $el = new Elixir($town->id);  $el->Load();  function NeedLife()  {      global $account;      global $town;      if($town->id != $account->htid)          return 0;      if(($account->life < 100) and ($account->life > 1))          return (int)ceil(100 - $account->life);      return 0;  }  if(isset($_POST['com']) and $_POST['com'] == USE_ELIXIR)  {   if($town->Lock() and ($town->modify == $_SERVER['REQUEST_TIME']))   {          $el->Load();    for($i = 1; $i<15 ;$i++)    {     $ek = 'ueid'.$i;     if(!isset($_POST[$ek]))      continue;     $_POST[$ek] = ValidNumber($_POST[$ek],true);     if(!$_POST[$ek])      continue;     $eli = 'e'.$i;     if(!$town->$eli or !($list[$i]->kind & 1))      continue;     if($town->$eli < $_POST[$ek])      $_POST[$ek] = $town->$eli;     if($i == 14 or $i == 7)              {                  if($_POST[$ek] > $el->Need($i, $_SERVER['REQUEST_TIME']))                      $_POST[$ek] = $el->Need($i, $_SERVER['REQUEST_TIME']);              }     if($i == 3)              {                  $_POST[$ek] = NeedLife();                  $life = $account->life + $_POST[$ek];                  if($life > 100)                      $life = '100';                  $account->SetFields(array('life' => $life));                  $town->AddFields(array('e3' => '-'.$_POST[$ek]));              }     elseif($_POST[$ek])              {                  $el->AddEffect($i, ELIXIR_GOOD, $_POST[$ek], $_SERVER['REQUEST_TIME'], $town->pop);                  $town->AddFields(array('e'.$i => '-'.$_POST[$ek]));              }    }    $town->UnLock();   }  }  ?>
<div>
<form action="<?php printf('building.php?bid=%s&amp;tid=%s&amp;show=%s',$bid, $town->id,USE_ELIXIR);?>" method="post">
<input type="hidden" name="com" value="<?php echo USE_ELIXIR;?>" />
<table>
<tr><td><?php echo $lang['Elixir'];?></td><td><?php echo $lang['Number'];?></td><td><?php echo $lang['Need'];?></td><td><?php echo $lang['Select'];?></td><td><?php echo $lang['Action'];?></td></tr>
<?php  $j =0;  $one = 1;  for($i = 1;$i<15;$i++)  {   $e = "e$i";   if($town->$e == 0 or !(($list[$i]->kind & 1))== 1)    continue;   $j++;   printf('<tr><td><img src="img/eli/%d.gif" class = "i30s" onclick="modal.Show(\'mo%d\');" alt = "%s" /></td>   <td><a href="javascript:void(0);" onclick="SetValues(\'ueid%d\',this.innerHTML);">%s</a></td><td>%s</td>   <td><input type="text" value = "0" name = "ueid%d" id = "ueid%d" /></td><td><input type="submit" value = "%s" /></td></tr>',          $i,$i,$list[$i]->name,$i,$town->$e,($i == 3) ? (NeedLife() != 0 ? NeedLife() : '-')              : (($el->Need($i,$_SERVER['REQUEST_TIME']) == 0) ? '-' : $el->Need($i,$_SERVER['REQUEST_TIME'])),$i,$i,$lang['Using']);  }  if(!$j)   printf('<tr><td colspan="4">%s</td></tr>',$lang['NoRecord']);  ?>
</table>
</form>
</div>
<?php  $sql = $dbo->ExectueQuery(sprintf('SELECT * FROM `%selixir_e` WHERE `tid` = \'%s\' AND `d` = \'0\' ORDER BY `modify` ', DB_PERFIX, $town->id));  if(!$dbo->RowsNumber($sql))  {   $dbo->Cancel($sql);   return;  }  ?>
<div>
<center><?php echo $lang['TownInEffect'];?></center>
<table>
<tr><td><?php echo $lang['Elixir'];?></td><td><?php echo $lang['Kind'];?></td><td><?php echo $lang['Number'];?></td><td><?php echo $lang['Total'];?></td><td><?php echo $lang['InDate'];?></td></tr>
<?php  $arr = array();  $arr[0] = array(1=>0,2=>0,3=>0,4=>0,5=>0,6=>0,7=>0,8=>0,9=>0,10=>0,11=>0,12=>0,13=>0,14=>0,15=>0);  $arr[1] = array(1=>0,2=>0,3=>0,4=>0,5=>0,6=>0,7=>0,8=>0,9=>0,10=>0,11=>0,12=>0,13=>0,14=>0,15=>0);  while($row = $dbo->Read($sql))  {   $arr[$row['kind']][$row['eid']] += $row['num'];   printf('<tr><td><img src="img/eli/%s.gif" alt="%s" class="i30" /></td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>',   $row['eid'],$list[$row['eid']]->name, $row['kind'] == ELIXIR_BAD ?  '<blink><font color="#ff0000">'.$lang['Bad'].'</font></blink>' : $lang['Good'],   $row['num'],$arr[$row['kind']][$row['eid']],    $form->Addtimer($row['modify'],    sprintf('building.php?bid=%s&amp;tid=%s&amp;show=%s',$bid, $town->id, USE_ELIXIR)));  }  ?>
</table>
</div>
</div>