<?php  $error = 0;      printf($lang['ExchangeRes'],EXTERA_TALANT);      if(isset($_POST) and isset($_POST['com']) and ($_POST['com'] == CHANGE_RESOURCE_MARKET))      {          if($town->Lock() and $account->Lock() and ($town->modify == $_SERVER['REQUEST_TIME']))          {                if($plus->HaveTalant(EXTERA_TALANT))              {                  $t1 = 0;                  $t2 = 0;                  $arr = array();                  for($i = 1; $i < 6; $i++)                  {                      $r = 'r'.$i;                      $p = 'exR'.$i;                      $_POST[$p] = (isset($_POST[$p]) ? ValidNumber($_POST[$p],true) : 0);                      if($i < 5)                      {                          if($_POST[$p] > $town->l1)                              $_POST[$p] = $town->l1;                      }                      else                      {                          if($_POST[$p] > $town->l2)                              $_POST[$p] = $town->l2;                      }                      $t1 += $_POST[$p];                      $t2 += (int)round($town->$r);                      $arr[$r] = (($town->$r > $_POST[$p]) ? -($town->$r - $_POST[$p]): ($_POST[$p] - $town->$r));                  }                  if($t1== $t2)                  {                      $town->AddFields($arr);                      $plus->ExchengeR($_POST);                  }                  elseif($t1 < $t2)                  {                      $ex = ($t2 - $t1)/5;                      for($i = 1;$i < 6; $i++)                          $arr['r'.$i] += $ex;                      $town->AddFields($arr);                      $plus->ExchengeR($_POST);                  }                  else                      $error = 1;              }          }          $account->UnLock();          $town->UnLock();      }  ?>
<form id = "fexr" action="<?php printf('building.php?bid=%s&amp;tid=%s&amp;show=%s',$bid,$town->id,CHANGE_RESOURCE_MARKET);?>" method="POST" >
<input type="hidden" name="com" value="<?php echo CHANGE_RESOURCE_MARKET;?>">
<table style="width: 462px;">
<?php      if($error)          printf('<tr><td colspan="6" class="error">%s</td></tr>',sprintf($lang['NotEnough'],$lang['Resource']));      printf('<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>',          $lang['r1'],$lang['r2'],$lang['r3'],$lang['r4'],$lang['r5'],$lang['Total']);      printf('<tr><td id = "fR1">%d</td><td id = "fR2">%d</td><td id = "fR3">%d</td><td id = "fR4">%d</td><td id = "fR5">%d</td><td id = "tR">%d</td></tr>',          round($town->r1),round($town->r2),round($town->r3),round($town->r4), round($town->r5),          round($town->r1) + round($town->r2)+  round($town->r3)+ round($town->r4)+ round($town->r5));  ?>
<tr><td><input type="text" name = "exR1" id = "exR1" value ="<?php echo round($town->r1);?>" style="width: 75px;" onkeyup="ExchangeResource();" onkeypress="ExchangeResource();"/></td>
<td><input type="text" name = "exR2" id = "exR2" value ="<?php echo round($town->r2);?>" style="width: 75px;" onkeyup="ExchangeResource();" onkeypress="ExchangeResource();"/></td>
<td><input type="text" name = "exR3" id = "exR3" value ="<?php echo round($town->r3);?>" style="width: 75px;" onkeyup="ExchangeResource();" onkeypress="ExchangeResource();"/></td>
<td><input type="text" name = "exR4" id = "exR4" value ="<?php echo round($town->r4);?>" style="width: 75px;" onkeyup="ExchangeResource();" onkeypress="ExchangeResource();"/></td>
<td><input type="text" name = "exR5" id = "exR5" value ="<?php echo round($town->r5);?>" style="width: 75px;" onkeyup="ExchangeResource();" onkeypress="ExchangeResource();"/></td>
<td id = "exR">0</td>
</tr>
<tr><td colspan="6"><img src="<?php echo ($plus->HaveTalant(EXTERA_TALANT) ? 'img/plus/h.gif' : 'img/plus/n.gif');?>" <?php if($plus->HaveTalant(EXTERA_TALANT)) echo 'OnClick="SubForm(\'fexr\');"';?> alt = "<?php          echo ($plus->HaveTalant(EXTERA_TALANT) ? $lang['Exchenge'] :          sprintf($lang['NotEnough'], $lang['Talant'])); ?>" class ="i30s"/></td></tr>
</table>
</form>