<?php  require_once('.//lib/dbo.php');  require_once('.//lib/form.php');  $player = $dbo->ExectueRow(sprintf('SELECT * FROM `%spoint` WHERE `owner` = \'%s\' AND `kind` = \'%s\'',DB_PERFIX,$account->id,PLAYER_KIND));  ?>
<table class="b_table">
<tr><td><?php echo $lang['Index'];?></td><td><?php echo $lang['Rank'];?></td><td><?php echo $lang['Name'];?></td>
<td><img src="img/troop/ap.gif" class="i30"  alt = "<?php echo $lang['AP'];?>"/></td></tr>
<?php  $dbo->ExectueQuery('SET @prev_value = 0;');  $dbo->ExectueQuery('SET @rank_count = 0;');  $sql = $dbo->ExectueQuery(sprintf('SELECT `t`.`owner` , `t`.`ap` , `t`.`rank` , `a`.`name` FROM ( SELECT `owner` , `ap` , CASE WHEN @prev_value = `ap` THEN @rank_count WHEN @prev_value := `ap` THEN @rank_count := @rank_count + 1 END AS `rank` FROM `%spoint` WHERE `kind` = \'%s\' ORDER BY `ap` DESC ) AS `t` LEFT JOIN `%saccount` AS `a` ON ( `t`.`owner` = `a`.`id` ) WHERE `a`.`id` > \'7\'', DB_PERFIX, PLAYER_KIND, DB_PERFIX));  $i =1;  while($row = $dbo->Read($sql))  {   if(($row['rank'] > 3)or($i > 10))    break;    printf('<tr><td>%d</td><td>%s</td><td>%s</td><td>%s</td></tr>',$i++,$row['rank'],$form->PlayerLink($row['owner'],$row['name']),$row['ap']);  }  $dbo->Cancel($sql);  printf('<tr><td>?</td><td>?</td><td>%s</td><td>%s</td></tr>',$account->name, $player['ap']);  ?>
</table><br  />
<table class="b_table">
<tr><td><?php echo $lang['Index'];?></td><td><?php echo $lang['Rank'];?></td><td><?php echo $lang['Name'];?></td>
<td><img src="img/troop/dp.gif" class="i30"  alt = "<?php echo $lang['DP'];?>"/></td></tr>
<?php  $dbo->ExectueQuery('SET @prev_value = 0;');  $dbo->ExectueQuery('SET @rank_count = 0;');  $sql = $dbo->ExectueQuery(sprintf('SELECT `t`.`owner` , `t`.`dp` , `t`.`rank` , `a`.`name` FROM ( SELECT `owner` , `dp` , CASE WHEN @prev_value = `dp` THEN @rank_count WHEN @prev_value := `dp` THEN @rank_count := @rank_count +1 END AS `rank` FROM `%spoint` WHERE `kind` = \'%s\' ORDER BY `dp` DESC ) AS `t` LEFT JOIN `%saccount` AS `a` ON ( `t`.`owner` = `a`.`id` ) WHERE `a`.`id` > \'7\'', DB_PERFIX, PLAYER_KIND, DB_PERFIX));  $i =1;  while($row = $dbo->Read($sql))  {   if(($row['rank'] > 3)or($i > 10))    break;   printf('<tr><td>%d</td><td>%s</td><td>%s</td><td>%s</td></tr>',$i++,$row['rank'],$form->PlayerLink($row['owner'],$row['name']),$row['dp']);  }  $dbo->Cancel($sql);  printf('<tr><td>?</td><td>?</td><td>%s</td><td>%s</td></tr>',$account->name, $player['dp']);  ?>
</table><br  />
<table class="b_table">
<tr><td><?php echo $lang['Index'];?></td><td><?php echo $lang['Rank'];?></td><td><?php echo $lang['Name'];?></td>
<td><img src="img/troop/tcr.gif" class="i30"  alt = "<?php echo $lang['M_2'];?>"/></td></tr>
<?php  $dbo->ExectueQuery('SET @prev_value = 0;');  $dbo->ExectueQuery('SET @rank_count = 0;');  $sql = $dbo->ExectueQuery(sprintf('SELECT `t`.`owner` , `t`.`plunder` , `t`.`rank` , `a`.`name` FROM ( SELECT `owner` , `plunder` , CASE WHEN @prev_value = `plunder` THEN @rank_count WHEN @prev_value := `plunder` THEN @rank_count := @rank_count +1 END AS `rank` FROM `%spoint` WHERE `kind` = \'%s\' ORDER BY `plunder` DESC ) AS `t` LEFT JOIN `%saccount` AS `a` ON ( `t`.`owner` = `a`.`id` ) WHERE `a`.`id` > \'7\'', DB_PERFIX, PLAYER_KIND, DB_PERFIX));  $i =1;  while($row = $dbo->Read($sql))  {   if(($row['rank'] > 3)or($i > 10))    break;   printf('<tr><td>%d</td><td>%s</td><td>%s</td><td>%s</td></tr>',$i++,$row['rank'],$form->PlayerLink($row['owner'],$row['name']),$row['plunder']);  }  $dbo->Cancel($sql);  printf('<tr><td>?</td><td>?</td><td>%s</td><td>%s</td></tr>',$account->name, $player['plunder']);  ?>
</table><br  />
<table class="b_table">
<tr><td><?php echo $lang['Index'];?></td><td><?php echo $lang['Rank'];?></td><td><?php echo $lang['Name'];?></td>
<td><img src="img/res/pop.gif" class="i30"  alt = "<?php echo $lang['Pop'];?>"/></td></tr>
<?php  $dbo->ExectueQuery('SET @prev_value = 0;');  $dbo->ExectueQuery('SET @rank_count = 0;');  $sql = $dbo->ExectueQuery(sprintf('SELECT `t`.`owner` , `t`.`pop` , `t`.`rank` , `a`.`name` FROM ( SELECT `owner` , `pop` , CASE WHEN @prev_value = `pop` THEN @rank_count WHEN @prev_value := `pop` THEN @rank_count := @rank_count +1 END AS `rank` FROM `%spoint` WHERE `kind` = \'%s\' ORDER BY `pop` DESC ) AS `t` LEFT JOIN `%saccount` AS `a` ON ( `t`.`owner` = `a`.`id` ) WHERE `a`.`id` > \'7\'', DB_PERFIX, PLAYER_KIND, DB_PERFIX));  $i =1;  while($row = $dbo->Read($sql))  {   if(($row['rank'] > 3)or($i > 10))    break;   printf('<tr><td>%d</td><td>%s</td><td>%s</td><td>%s</td></tr>',$i++,$row['rank'],$form->PlayerLink($row['owner'],$row['name']),$row['pop']);  }  $dbo->Cancel($sql);  printf('<tr><td>?</td><td>?</td><td>%s</td><td>%s</td></tr>',$account->name, $player['pop']);  ?>
</table><br  />
<table class="b_table">
<tr><td><?php echo $lang['Index'];?></td><td><?php echo $lang['Rank'];?></td><td><?php echo $lang['Name'];?></td>
<td><?php echo $lang['M_N_5'];?></td></tr>
<?php  $dbo->ExectueQuery('SET @prev_value = 0;');  $dbo->ExectueQuery('SET @rank_count = 0;');  $sql = $dbo->ExectueQuery(sprintf('SELECT `t`.`owner` , `t`.`honor` , `t`.`rank` , `a`.`name` FROM ( SELECT `owner` , `honor` , CASE WHEN @prev_value = `honor` THEN @rank_count WHEN @prev_value := `honor` THEN @rank_count := @rank_count + 1 END AS `rank` FROM `%spoint` WHERE `kind` = \'%s\' ORDER BY `honor` DESC ) AS `t` LEFT JOIN `%saccount` AS `a` ON ( `t`.`owner` = `a`.`id` ) WHERE `a`.`id` > \'7\'', DB_PERFIX, PLAYER_KIND, DB_PERFIX));  $i =1;  while($row = $dbo->Read($sql))  {   if(($row['rank'] > 3)or($i > 10))    break;   printf('<tr><td>%d</td><td>%s</td><td>%s</td><td>%s</td></tr>',$i++,$row['rank'],$form->PlayerLink($row['owner'],$row['name']),$row['honor']);  }  $dbo->Cancel($sql);  printf('<tr><td>?</td><td>?</td><td>%s</td><td>%s</td></tr>',$account->name, $player['honor']);  ?>
</table>