<?php  require_once('lib/defines.php');  require_once('eng/forum/post.php');  require_once('lib/form.php');  if(isset($_GET['uid']) and is_numeric($_GET['uid']))   $uid = (int)$_GET['uid'];  else   $uid = $account->uid;    if(!$uid or !isset($_GET['id']))   $session->Href('block.php');     $topic->Load($uid);  $t = $topic->Topics($_GET['id']);  if(!$t or !$topic->IsMember($session->pid, $_GET['id']))   $session->Href('block.php');  $post = new Post($t->id);  $count = $post->CountRow();  $page = isset($_GET['page']) ? (int)$_GET['page'] : 0;  $row = isset($_GET['row']) ? (int)$_GET['row'] : 10;  $page = isset($_GET['last'])?(int)(($post->GetPage($_GET['last']) - 1)/$row): $page;  if($row > 100 or !$plus->HavePlus('pb'))   $row = 10;  if($page * $row > $count)   $page = 0;    $post->Load($row, $page);  ?>
<table style="width:670px;">
<tr><td class="w90"><?php echo $lang['Name'];?></td><td class="w540"><?php echo $lang['Text'];?></td><td class="w40"><?php echo $lang['Action'];?></td></tr>
<?php    if($count)  {   $i = 0;   foreach($post->_list as $l)   {    $like = $post->IsLike($l->id, $account->id);    echo '<tr><td>';    printf('%s<br />',$form->PlayerLink($l->pid,$l->pname));    printf('%s : <span id = "s_%d">%s</span><br />',$lang['Like'],$i,$l->like);    printf('<img id = "i_%d" src = "img/all/like%s.gif" alt ="%s" onClick="ChangLike(this,\'%s\');"/><br />',     $i, $like,$like ? $lang['Like']:$lang['UnLike'], $l->id);    if($l->eid)     printf('%s<br />',$form->PlayerLink($l->eid,$l->ename));    printf('%s',DateToString($l->modify));    printf('</td><td>%s</td>',$form->Replace($l->message));    if($session->Permission(EDIT_FROM) or $l->pid == $account->id)    printf('<td>%s</td>',$form->AhrefImg('/forum.php?show='.E_POST.'&amp;uid='.$uid.'&amp;id='.$t->id.'&amp;poid='.$l->id,     'i16','img/all/sys.gif',$lang['Edit']));    $i++;    echo '</tr>';   }  }  else   printf('<tr><td class = "center" colspan="3">%s</td></tr>',$lang['NoRecord']);    ?>
<tr><td class="center" colspan="3"><input type="button" onclick="window.location='<?php printf('forum.php?show=%s&uid=%s&id=%s', N_POST,$uid,$t->id);?>'" value = "<?php echo $lang['New'];?>"/></td></tr>
<tr><td><?php echo $lang['PageNumber'];?></td><td colspan="2">
<?php echo Paging($count, sprintf('forum.php?show=%s&amp;uid=%s&amp;id=%s&amp;',POST, $uid,$t->id), $row, $page);?></td></tr>
<?php  if($plus->HavePlus('pb'))   printf('<tr><td colspan="3">%s</td></tr>',    $form->AddPagingForm('forum',POST,$page,$row,array('uid' => $uid ,'id' => $t->id)));  ?>
</table>
<div class="center Pooling"><br/><br/><?php echo $form->Ahref('/forum.php?show='.TOPIC.'&amp;uid='.$uid,$lang['Return']);?></div>