<?php  require_once('lib/defines.php');  require_once('eng/forum/topic.php');  require_once('lib/utility.php');  require_once('.//lib/form.php');  require_once('eng/sec/session.php');  require_once('lng/per.php');  require_once('eng/sec/user.php');    if(isset($_GET['uid']) and is_numeric($_GET['uid']))   $uid = (int)$_GET['uid'];  else   $uid = $account->uid;    if(!$uid)   $session->Href('block.php');    $topic->Load($uid);  function ShowPostAddress($id,$uid,$poid,$name,$per)  {   global $form;   global $lang;   if($per)    printf('<tr><td id = "tp%d" class="showHint">%s</td><td class="w50">%s</td></tr>',     $id,$form->Ahref('/forum.php?show='.POST.'&amp;uid='.$uid.'&amp;id='.$poid,$name),      $form->AhrefImg('/forum.php?show='.EDIT.'&amp;uid='.$uid.'&amp;id='.$poid,'i16','img/all/sys.gif',$lang['Edit']));   else    printf('<tr><td id="tp%d" class="t200">%s</td><td>&nbsp;</td></tr>',     $id,$form->Ahref('/forum.php?show='.POST.'&amp;uid='.$uid.'&amp;id='.$poid,$name));  }  ?>

<table class="center">
<tr><td colspan="2" class="tBold f_m_back"><?php echo $lang['Open'];?></td></tr>
<?php  $list = $topic->GetTopic(ALL_USER);  $Per = $session->Permission(EDIT_FROM) and $account->uid == $uid;  $i=0;  if(!count($list))   printf('<tr><td colspan="2" class="rightAlign rp5">%s</td></tr>',$lang['NoRecord']);  else  {   foreach($list as $l)   {    ShowPostAddress($i, $uid, $l->id, $l->name, $Per);    $form->AddText('tp'.$i,$l->desc);    $i++;   }  }  if($Per)  {   printf('<tr><td colspan="2" class="rp5">%s</td></tr>',$form->Ahref('/forum.php?show='.NEW_TOPIC.'&amp;uid='.$uid,$lang['New']));  }  ?>

<tr><td colspan="2" class="tBold f_m_back"><?php echo $lang['Union'];?></td></tr>
<?php  $list = $topic->GetTopic(UNION_MEMBER);  if(!count($list))   printf('<tr><td colspan="2" class="rightAlign rp5">%s</td></tr>',$lang['NoRecord']);  else  {   foreach($list as $l)   {    ShowPostAddress($i, $uid, $l->id, $l->name, $Per);    $form->AddText('tp'.$i,$l->desc);    $i++;   }  }  if($session->Permission(EDIT_FROM) and $account->uid == $uid)  {   printf('<tr><td colspan="2" class="rp5">%s</td></tr>',$form->Ahref('/forum.php?show='.NEW_TOPIC.'&amp;uid='.$uid,$lang['New']));  }  ?>

<tr><td colspan="2" class="tBold f_m_back"><?php echo $lang['Private'];?></td></tr>
<?php  $list = $topic->GetTopic(INVITED_MEMBER);  $s = true;  foreach($list as $l)  {   if($Per)   {    ShowPostAddress($i, $uid, $l->id, $l->name, $Per);    $form->AddText('tp'.$i,$l->desc);    $i++;    $s = false;   }   elseif($topic->IsMember($l->id,$account->id))   {    ShowPostAddress($i, $uid, $l->id, $l->name, $Per);    $form->AddText('tp'.$i,$l->desc);    $s = false;    $i++;   }  }  if($s)   printf('<tr><td colspan="2" class="rightAlign rp5">%s</td></tr>',$lang['NoRecord']);    if($Per)  {   printf('<tr><td colspan="2" class="rp5">%s</td></tr>',$form->Ahref('/forum.php?show='.NEW_TOPIC.'&amp;uid='.$uid,$lang['New']));  }  ?>
</table>
